# fly.toml app configuration file generated for stow-kiosk-deploy-winter-dream-8582 on 2025-03-19T23:53:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stow-kiosk"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
[deploy]
  release_command = "npm run setup && npm run seed"

[[vm]]
  memory = 1024
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "stow_kiosk_data"
  destination = "/data"
